# Generated by Django 3.1.3 on 2020-11-25 00:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=45)),
                ('InseridoPor', models.CharField(max_length=45, null=True)),
                ('DataInsercao', models.DateTimeField(auto_now_add=True)),
                ('AtualizadoPor', models.CharField(max_length=45, null=True)),
                ('DataDeAtualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=45)),
                ('InseridoPor', models.CharField(max_length=45, null=True)),
                ('DataInsercao', models.DateTimeField(auto_now_add=True)),
                ('AtualizadoPor', models.CharField(max_length=45, null=True)),
                ('DataDeAtualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=45)),
                ('NomeGuerra', models.CharField(max_length=45)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('DataDeNascimento', models.DateField(null=True)),
                ('Telefone', models.CharField(max_length=45, null=True)),
                ('RITEx', models.CharField(max_length=45, null=True)),
                ('FlgCiente', models.IntegerField(default=0)),
                ('Imagem', models.ImageField(upload_to='', verbose_name=models.ImageField(blank=True, null=True, upload_to='militares'))),
                ('FlgTelegram', models.IntegerField(default=0)),
                ('FlgWhatsApp', models.IntegerField(default=0)),
                ('InseridoPor', models.CharField(max_length=45, null=True)),
                ('DataInsercao', models.DateTimeField(auto_now_add=True)),
                ('AtualizadoPor', models.CharField(max_length=45, null=True)),
                ('DataDeAtualizacao', models.DateTimeField(auto_now=True)),
                ('FlgAtivo', models.IntegerField(default=0)),
                ('graduacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminstration.graduacao')),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminstration.secao')),
            ],
        ),
    ]
