# Generated by Django 3.1.3 on 2020-11-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='Imagem',
            field=models.ImageField(blank=True, null=True, upload_to='militares/'),
        ),
    ]
