# Generated by Django 3.1.3 on 2020-11-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0002_auto_20201124_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='FlgCiente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='militar',
            name='FlgTelegram',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='militar',
            name='FlgWhatsApp',
            field=models.BooleanField(default=True),
        ),
    ]
