# Generated by Django 3.1.3 on 2020-11-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0003_auto_20201124_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='FlgAtivo',
            field=models.BooleanField(default=True),
        ),
    ]
